# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  enableMultiRepo: true
  enableLegacyFields: true
  policyController:
    enabled: true
  clusterName: krmapihost-nauvoo-test-cc
  git:
    policyDir: /quickstart/config-sync
    secretType: none
    syncBranch: main
    syncRepo: https://github.com/GoogleCloudPlatform/anthos-config-management-samples
  sourceFormat: hierarchy 